package com.evolution.sbt.kagi

import java.nio.charset.StandardCharsets
import java.nio.file.*
import scala.jdk.CollectionConverters.*

/**
 * Module dependency lock file format for [[KagiPlugin]].
 *
 * The file consists of
 *   - dependency coordinates (one per line): `<groupId>:<artifactId>:<version>`
 *   - empty lines - ignored
 *   - comment lines starting with `'#'` - ignored
 *
 * For readability, dependencies are sorted and grouped into sections by `groupId`,
 * separated with a comment and a newline.
 */
private[kagi] object KagiLockFile {

  private val Header: String =
    """|# Dependency lock file generated by sbt-kagi-plugin
      |# Run "sbt kagiDependencyLockWrite" to update
      |# DO NOT EDIT MANUALLY!
      |""".stripMargin

  /**
   * Writes a module dependency set to a lock file.
   *
   * Fails if the directory path to the file doesn't exist.
   */
  def write(filePath: Path, dependencySet: KagiDependencySet): Unit = {
    val textBuilder = new StringBuilder(
      Header.length + dependencySet.size * 64, // good-enough heuristic
    )

    textBuilder ++= Header

    dependencySet.elems.toVector.groupBy(_.groupId).toVector.sortBy(_._1).foreach {
      case (groupId, groupDeps) =>
        textBuilder += '\n'
        textBuilder ++= s"# $groupId\n"
        groupDeps.foreach { dep =>
          textBuilder ++= s"$dep\n"
        }
    }

    Files.writeString(
      filePath,
      textBuilder.toString(),
      StandardCharsets.UTF_8,
    )
    ()
  }

  /**
   * Reads a dependency set from a lock file.
   *
   * If the lock file doesn't exist, an empty set is returned.
   */
  def read(filePath: Path): KagiDependencySet = {
    if (Files.notExists(filePath)) {
      KagiDependencySet.empty
    } else {
      val lineStream = Files.lines(filePath, StandardCharsets.UTF_8)
      try {
        KagiDependencySet.from(
          lineStream.iterator().asScala
            .map(_.strip())
            .filter(!_.startsWith("#"))
            .filter(_.nonEmpty)
            .map(KagiDependency.parse),
        )
      } finally {
        lineStream.close()
      }
    }
  }
}
