package com.evolution.sbt.kagi

import java.nio.charset.StandardCharsets
import java.nio.file.*
import scala.jdk.CollectionConverters.*

private[kagi] object KagiLockFile {

  private val Header: String =
    """|# Dependency lock file generated by sbt-kagi-plugin
      |# Run "sbt kagiDependencyLockWrite" to update
      |# DO NOT EDIT MANUALLY!
      |""".stripMargin

  def write(filePath: Path, dependencySet: KagiDependencySet): Unit = {
    val textBuilder = new StringBuilder(
      Header.length + dependencySet.size * 64, // good-enough heuristic
    )

    textBuilder ++= Header

    dependencySet.elems.toVector.groupBy(_.groupId).toVector.sortBy(_._1).foreach {
      case (groupId, groupDeps) =>
        textBuilder += '\n'
        textBuilder ++= s"# $groupId\n"
        groupDeps.foreach { dep =>
          textBuilder ++= s"$dep\n"
        }
    }

    Files.writeString(
      filePath,
      textBuilder.toString(),
      StandardCharsets.UTF_8,
    )
    ()
  }

  def read(filePath: Path): KagiDependencySet = {
    if (Files.notExists(filePath)) {
      KagiDependencySet.empty
    } else {
      KagiDependencySet.from(
        Files.lines(filePath, StandardCharsets.UTF_8).iterator().asScala
          .map(_.strip())
          .filter(!_.startsWith("#"))
          .filter(_.nonEmpty)
          .map(KagiDependency.parse),
      )
    }
  }
}
