package com.evolution.sbt.kagi

import java.nio.charset.StandardCharsets
import java.nio.file.Files

class KagiLockFileTest extends munit.FunSuite {

  private val tmpDir = FunFixture[java.nio.file.Path](
    setup = _ => Files.createTempDirectory("kagi-lock-test"),
    teardown = dir => {
      Files.walk(dir).sorted(java.util.Comparator.reverseOrder()).forEach(Files.delete(_))
    },
  )

  tmpDir.test("write and read roundtrip preserves dependency set") { dir =>
    val deps = KagiDependencySet(
      KagiDependency("com.example", "lib-a", "1.0"),
      KagiDependency("com.example", "lib-b", "2.0"),
      KagiDependency("org.other", "utils", "3.0"),
    )
    val path = dir.resolve("test.lock.txt")

    KagiLockFile.write(path, deps)
    val result = KagiLockFile.read(path)

    assertEquals(result, deps)
  }

  tmpDir.test("read nonexistent file returns empty set") { dir =>
    val result = KagiLockFile.read(dir.resolve("nonexistent.lock.txt"))
    assertEquals(result, KagiDependencySet.empty)
  }

  tmpDir.test("written file contains header") { dir =>
    val deps = KagiDependencySet(KagiDependency("org.example", "lib", "1.0"))
    val path = dir.resolve("test.lock.txt")

    KagiLockFile.write(path, deps)
    val content = Files.readString(path, StandardCharsets.UTF_8)

    assert(content.startsWith("# Dependency lock file generated by sbt-kagi-plugin"))
    assert(content.contains("# DO NOT EDIT MANUALLY!"))
  }

  tmpDir.test("written file groups dependencies by groupId") { dir =>
    val deps = KagiDependencySet(
      KagiDependency("com.alpha", "lib-a", "1.0"),
      KagiDependency("com.alpha", "lib-b", "2.0"),
      KagiDependency("org.beta", "utils", "3.0"),
    )
    val path = dir.resolve("test.lock.txt")

    KagiLockFile.write(path, deps)
    val content = Files.readString(path, StandardCharsets.UTF_8)

    assert(content.contains("# com.alpha"))
    assert(content.contains("# org.beta"))
    assert(content.contains("com.alpha:lib-a:1.0"))
    assert(content.contains("com.alpha:lib-b:2.0"))
    assert(content.contains("org.beta:utils:3.0"))
  }

  tmpDir.test("groups are sorted alphabetically by groupId") { dir =>
    val deps = KagiDependencySet(
      KagiDependency("z.group", "lib", "1.0"),
      KagiDependency("a.group", "lib", "1.0"),
      KagiDependency("m.group", "lib", "1.0"),
    )
    val path = dir.resolve("test.lock.txt")

    KagiLockFile.write(path, deps)
    val content = Files.readString(path, StandardCharsets.UTF_8)

    val aIdx = content.indexOf("# a.group")
    val mIdx = content.indexOf("# m.group")
    val zIdx = content.indexOf("# z.group")
    assert(aIdx < mIdx, s"a.group ($aIdx) should come before m.group ($mIdx)")
    assert(mIdx < zIdx, s"m.group ($mIdx) should come before z.group ($zIdx)")
  }

  tmpDir.test("read ignores comments and blank lines") { dir =>
    val path = dir.resolve("test.lock.txt")
    Files.writeString(
      path,
      """|# header comment
         |
         |# group comment
         |org.example:lib:1.0
         |
         |  org.example:lib2:2.0  
         |""".stripMargin,
      StandardCharsets.UTF_8,
    )

    val result = KagiLockFile.read(path)
    assertEquals(
      result,
      KagiDependencySet(
        KagiDependency("org.example", "lib", "1.0"),
        KagiDependency("org.example", "lib2", "2.0"),
      ),
    )
  }

  tmpDir.test("write empty set produces only header") { dir =>
    val path = dir.resolve("test.lock.txt")
    KagiLockFile.write(path, KagiDependencySet.empty)

    val result = KagiLockFile.read(path)
    assertEquals(result, KagiDependencySet.empty)
  }
}
